### ISSUE TITLE
"cless" (without filename)

### ISSUE THREAD

**Issue by martinlindhe** [tanakh/cless#1]
Hello. First, awesome program!

I saw it by accident while running "brew update".

Anyway. It is working great when i'm using it as expected.

But when i just manage to fail to do it properly (ie just run "cless")
it stucks in full screen, which i could eventually leave by CTRL-C and then Q.

My less (i guess bsd less, on osx) instead prints:
Missing filename ("less --help" for help)

Also, pipe to cless dont give me colors :-(

cat gulpfile.js | cless   => non colored

**Comment by pthariensflame** [comment]
For the colors when piping, try the `-l` (or `--lang`) option.  For your example, try:

``` bash
cat gulpfile.js | cless -l js
```

As for the other problem, I guess we just have to get @tanakh's attention.  :(

**Comment by tanakh** [comment]
Hello, thank you for using.
cless detect the language of file from its filename.
So when piping stdout content to cless, you need to specify language explicitly by --lang option.
Invoking without filename, I think it should be error, too.
I will fix so.

**Comment by martinlindhe** [comment]
thanks for clarifying! again, thanks for a great utility ;-)

**Comment by martinlindhe** [comment]
i would try to contribute if i could. but i'm not even familiar with what language this was written in, haskell?

**Comment by pthariensflame** [comment]
Yes, Haskell.  :)

**Comment by martinlindhe** [comment]
I think the issue has been resolved now. Haven't tried to build this from source, just got a 0.3.0.0 version though homebrew.

Now it does:

```
> cless 
cless: Missing filename ("cless --help" for help)
```
